/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124462-ga327bc0561-20260514"
#endif /* AVUTIL_FFVERSION_H */
