/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124399-g5c44245878-20260505"
#endif /* AVUTIL_FFVERSION_H */
